export default [
    {
        title:'首页',
        key:'/admin/home'
    },
    {
        title:'UI',
        key:'/admin/ui',
        children:[
            {
                title:'按钮',
                key:'/admin/ui/button',
            },
            {
                title:'弹框',
                key:'/admin/ui/modals',
            },
        ]
    },
    {
        title:'UI',
        key:'/admin/ui',
        children:[
            {
                title:'按钮',
                key:'/admin/ui/button',
            },
            {
                title:'弹框',
                key:'/admin/ui/modals',
            },
        ]
    },
    {
        title:'权限设置',
        key:'/admin/ui',
    },
]